name: Update Shared Submodule

on:
  repository_dispatch:
    types: [shared-updated]

jobs:
  update-submodule:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Host Repository
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set git config for commits
        run: |
          git config user.email "host.repository@gihub.com"
          git config user.name "host repository"
          
      - name: Update Submodule to Latest Master
        run: |
          cd shared
          git checkout master
          git rebase origin master
          cd ..
          git add shared
          git commit -m "Updated shared submodule to latest master"
          git push https://github.com/${{ github.repository }}.git HEAD:master
